class EventTypes:
    TRAIN_DELAY_DETECTED = "TRAIN_DELAY_DETECTED"
    SURGE_RISK_UPDATED = "SURGE_RISK_UPDATED"
    SURGE_RISK_CRITICAL = "SURGE_RISK_CRITICAL"
    ACTION_CARD_GENERATED = "ACTION_CARD_GENERATED"
    PA_ANNOUNCEMENT_CREATED = "PA_ANNOUNCEMENT_CREATED"
    ALERT_CONFIRMED = "ALERT_CONFIRMED"
    ALERT_BROADCASTED = "ALERT_BROADCASTED"
